on:
  push:
    branches: main

name: publish

jobs:
  publish:
    runs-on: macOS-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUBPAT }}
      TORCH_INSTALL: 1
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install system requirements
        run: |
          brew install pandoc

      - name: Build design specification
        run: |
          install.packages("bookdown")
          bookdown::render_book(input = "index.Rmd", output_format = "bookdown::gitbook")
        shell: Rscript {0}

      - name: Publish design specification
        run: |
          ./inst/publish.sh
